name: Update WakaTime

on:
  push:
    branches: ["*"]
  schedule:
    - cron: "* */12 * * *"

jobs:
  wakatime:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_PROFILE_VIEWS: "True"
          SHOW_OS: "True"
          SHOW_TIMEZONE: "True"
          SHOW_PROJECTS: "True"
          SHOW_EDITORS: "True"
          SHOW_SHORT_INFO: "True"
          SHOW_LOC_CHART: "True"
